name: Deploy To Test Server

on:
    push:
        branches: [ develop ]

jobs:
    deploy:
        environment:
            name: INTEGRATION
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Dump secret to env files
                uses: SpicyPizza/create-envfile@v1
                with:
                    envkey_DEPLOY_ENV: ${{ secrets.ENV }}
                    envkey_DEPLOY_TEST: ${{ secrets.TEST }}
                    filename: .env

            -   name: Echo Env
                run: cat .env
